"""Initial Commit

Revision ID: 3b800a20d223
Revises: 
Create Date: 2026-05-05 15:27:33.814740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b800a20d223'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('project_uuid'),
    sa.UniqueConstraint('project_uuid')
    )
    op.create_index('ix_project_name', 'projects', ['project_name'], unique=False)
    op.create_table('assets',
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=255), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=False),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asset_project_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_project_uuid'], ['projects.project_uuid'], ),
    sa.PrimaryKeyConstraint('asset_uuid'),
    sa.UniqueConstraint('asset_uuid')
    )
    op.create_index('ix_asset_project_uuid', 'assets', ['asset_project_uuid'], unique=False)
    op.create_index('ix_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_table('datachunks',
    sa.Column('datachunk_uuid', sa.UUID(), nullable=False),
    sa.Column('datachunk_text', sa.String(length=2048), nullable=False),
    sa.Column('datachunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('datachunk_order', sa.Integer(), nullable=True),
    sa.Column('chunk_project_uuid', sa.UUID(), nullable=True),
    sa.Column('chunk_asset_uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_asset_uuid'], ['assets.asset_uuid'], ),
    sa.ForeignKeyConstraint(['chunk_project_uuid'], ['projects.project_uuid'], ),
    sa.PrimaryKeyConstraint('datachunk_uuid'),
    sa.UniqueConstraint('datachunk_uuid')
    )
    op.create_index('ix_datachunk_asset_uuid', 'datachunks', ['chunk_asset_uuid'], unique=False)
    op.create_index('ix_datachunk_project_uuid', 'datachunks', ['chunk_project_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_datachunk_project_uuid', table_name='datachunks')
    op.drop_index('ix_datachunk_asset_uuid', table_name='datachunks')
    op.drop_table('datachunks')
    op.drop_index('ix_asset_type', table_name='assets')
    op.drop_index('ix_asset_project_uuid', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_project_name', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
