"""fix

Revision ID: 5cc3288d6c1e
Revises: 3b800a20d223
Create Date: 2026-05-19 09:24:04.755659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc3288d6c1e'
down_revision: Union[str, None] = '3b800a20d223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'assets', ['asset_uuid'])
    op.add_column('datachunks', sa.Column('datachunk_project_uuid', sa.UUID(), nullable=True))
    op.add_column('datachunks', sa.Column('datachunk_asset_uuid', sa.UUID(), nullable=True))
    op.drop_index('ix_datachunk_asset_uuid', table_name='datachunks')
    op.create_index('ix_datachunk_asset_uuid', 'datachunks', ['datachunk_asset_uuid'], unique=False)
    op.drop_index('ix_datachunk_project_uuid', table_name='datachunks')
    op.create_index('ix_datachunk_project_uuid', 'datachunks', ['datachunk_project_uuid'], unique=False)
    op.create_unique_constraint(None, 'datachunks', ['datachunk_uuid'])
    op.drop_constraint('datachunks_chunk_project_uuid_fkey', 'datachunks', type_='foreignkey')
    op.drop_constraint('datachunks_chunk_asset_uuid_fkey', 'datachunks', type_='foreignkey')
    op.create_foreign_key(None, 'datachunks', 'projects', ['datachunk_project_uuid'], ['project_uuid'])
    op.create_foreign_key(None, 'datachunks', 'assets', ['datachunk_asset_uuid'], ['asset_uuid'])
    op.drop_column('datachunks', 'chunk_project_uuid')
    op.drop_column('datachunks', 'chunk_asset_uuid')
    op.drop_index('ix_project_name', table_name='projects')
    op.create_index('ix_project_uuid', 'projects', ['project_name'], unique=False)
    op.create_unique_constraint(None, 'projects', ['project_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_index('ix_project_uuid', table_name='projects')
    op.create_index('ix_project_name', 'projects', ['project_name'], unique=False)
    op.add_column('datachunks', sa.Column('chunk_asset_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('datachunks', sa.Column('chunk_project_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'datachunks', type_='foreignkey')
    op.drop_constraint(None, 'datachunks', type_='foreignkey')
    op.create_foreign_key('datachunks_chunk_asset_uuid_fkey', 'datachunks', 'assets', ['chunk_asset_uuid'], ['asset_uuid'])
    op.create_foreign_key('datachunks_chunk_project_uuid_fkey', 'datachunks', 'projects', ['chunk_project_uuid'], ['project_uuid'])
    op.drop_constraint(None, 'datachunks', type_='unique')
    op.drop_index('ix_datachunk_project_uuid', table_name='datachunks')
    op.create_index('ix_datachunk_project_uuid', 'datachunks', ['chunk_project_uuid'], unique=False)
    op.drop_index('ix_datachunk_asset_uuid', table_name='datachunks')
    op.create_index('ix_datachunk_asset_uuid', 'datachunks', ['chunk_asset_uuid'], unique=False)
    op.drop_column('datachunks', 'datachunk_asset_uuid')
    op.drop_column('datachunks', 'datachunk_project_uuid')
    op.drop_constraint(None, 'assets', type_='unique')
    # ### end Alembic commands ###
